version: '3.8'

services:
  db:
    image: postgres:15
    container_name: popcorn_db
    restart: always
    environment:
      POSTGRES_USER: popcorn_palace
      POSTGRES_PASSWORD: popcorn_palace
      POSTGRES_DB: popcorn_palace
    ports:
      - '5432:5432'
    networks:
      - popcorn_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  popcorn_network:

volumes:
  db_data:
